### ISSUE TITLE
Infantry interaction model has some issues

### ISSUE THREAD

**Issue by boxed** [acunniffe/ghq#104]
I have played against the bot a few times and two things happen to me with artillery a LOT:

1. I want to move, but it rotates (I assume I click outside the move circles? I think rotating in place should require clicking the artillery again or something)
2. I moved and then try to point it straight north, but the artillery now points NW.

**Comment by APTy** [comment]
@boxed thanks for the feedback!

Based on your input and similar from others, we're working on an improved UX for artillery movement and rotation. We'll circle back here with updates soon

**Comment by boxed** [comment]
I think it got worse on iOS now. I don't get the choice to orient anymore, leading to disaster :)

**Comment by APTy** [comment]
Hey @boxed this should be fixed on mobile now, but please re-open if you have any more issues!
