### ISSUE TITLE
Docs for running/developing

### ISSUE THREAD

**Issue by boxed** [acunniffe/ghq#112]
I'm not into the JS ecosystem, so it's a bit hard to figure out how to run this locally. I saw there was a yarn lock file so I tried `yarn run dev` but that printed error messages:

```
 ⨯ Internal error: Error: @clerk/clerk-react: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
```

I just want to run this locally, surely I don't need to setup something with clerk (whatever that is)?

**Comment by acunniffe** [comment]
Hey @boxed - good callout. We need to make it possible to develop core game logic + UI without all the SaaS tools we use to power multiplayer.  

We'll work on this as our first task today. Probably will look like a `dev:local` vs a `dev:multiplayer`

Welcome to GHQ! When did you discover the game?

**Comment by boxed** [comment]
Hacker News. Barnes & Noble won't ship to Sweden so I built a set with lego to play at home. But it's been hard to get my family to play 🤣

**Comment by acunniffe** [comment]
Nice! We're in NYC. Started playing over the board and then realized we were using most of our brain power computing allowed moved in our heads. We built this mainly to decrease the cognitive load and make our games could get more interesting but then friends wanted to play too.

**Comment by boxed** [comment]
I think you need to internalize the valid moves anyway, just like in chess.

**Comment by APTy** [comment]
@boxed check out [CONTRIBUTING.md](https://github.com/acunniffe/ghq/blob/main/docs/CONTRIBUTING.md), hot off the press!

For now you'll need to `export NEXT_PUBLIC_GHQ_FRONTEND_ONLY=true` and then you should be able to `yarn run dev` and navigate to http://localhost:3000/local and be able to work on the core game logic 🔥
