### ISSUE TITLE
Artillery rotation thoughts so far

### ISSUE THREAD

**Issue by APTy** [acunniffe/ghq#120]
## Artillery doesn't rotate when clicking on a square that contains a piece

To reproduce:

1. Click on artillery
2. Click on new square to move it there
3. Click on a non-empty square to rotate it (either on its own square or a square with infantry on it)
4. The piece resets

This is a little unexpected (sample size of 3 people), I think most people would expect that while the piece is rotating, you could click anywhere and it would rotate.

<img width="161" alt="Screenshot 2024-11-19 at 5 03 43 PM" src="https://github.com/user-attachments/assets/734f79d6-1f26-49a4-9ad5-df043e85f397">

## Artillery doesn't rotate to the square you click on

Because of geometry, you can have your mouse on the square directly to the left of an artillery, but it will point `SW`, even though you'd expect it to point `W` (onto the square you're clicking). Rather than angle calculations, it might be better to detect what _square_ was clicked, and use that to calculate the orientation.

<img width="226" alt="Screenshot 2024-11-19 at 4 55 46 PM" src="https://github.com/user-attachments/assets/5dd54d59-e619-4808-a55f-0e981cdca454">

## Artillery doesn't update it's bombardment squares during rotation

This is more aesthetic, but I think it'd be very nice if the bombardment squares were updated (maybe with some variation to show it's planned not actual), so that (a) it's very obvious to the player that they're rotating something, and (b) they get a good preview of what's about to happen

**Comment by acunniffe** [comment]
Fixed the first one here https://github.com/acunniffe/ghq/commit/d6723292fc00b6c950d1340d6f9f904de89a0444

**Comment by acunniffe** [comment]
Fixed the rotation offset issue in https://github.com/acunniffe/ghq/commit/55bcad1de858052e4f5468a349fe76c1fe29aebb
